"""Add family and baby models

Revision ID: ca9d8d3bbd31
Revises: 002
Create Date: 2026-02-11 11:47:08.135176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9d8d3bbd31'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.create_table('babies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_babies_id'), 'babies', ['id'], unique=False)
    op.create_table('family_users',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('family_id', 'user_id')
    )

    with op.batch_alter_table('contractions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_contractions_baby_id', 'babies', ['baby_id'], ['id'])

    with op.batch_alter_table('diapers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_diapers_baby_id', 'babies', ['baby_id'], ['id'])

    with op.batch_alter_table('feedings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_feedings_baby_id', 'babies', ['baby_id'], ['id'])

    with op.batch_alter_table('growths', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_growths_baby_id', 'babies', ['baby_id'], ['id'])

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_schedules_baby_id', 'babies', ['baby_id'], ['id'])

    with op.batch_alter_table('sleeps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_sleeps_baby_id', 'babies', ['baby_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sleeps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sleeps_baby_id', type_='foreignkey')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_schedules_baby_id', type_='foreignkey')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('growths', schema=None) as batch_op:
        batch_op.drop_constraint('fk_growths_baby_id', type_='foreignkey')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('feedings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_feedings_baby_id', type_='foreignkey')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('diapers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_diapers_baby_id', type_='foreignkey')
        batch_op.drop_column('baby_id')

    with op.batch_alter_table('contractions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_contractions_baby_id', type_='foreignkey')
        batch_op.drop_column('baby_id')

    op.drop_table('family_users')
    op.drop_index(op.f('ix_babies_id'), table_name='babies')
    op.drop_table('babies')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###