"""Add family and baby models

Revision ID: ca9d8d3bbd31
Revises: 002
Create Date: 2026-02-11 11:47:08.135176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9d8d3bbd31'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_id'), 'families', ['id'], unique=False)
    op.create_index(op.f('ix_families_invite_code'), 'families', ['invite_code'], unique=True)
    op.create_table('babies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_babies_id'), 'babies', ['id'], unique=False)
    op.create_table('family_users',
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('family_id', 'user_id')
    )
    op.add_column('contractions', sa.Column('baby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contractions', 'babies', ['baby_id'], ['id'])
    op.add_column('diapers', sa.Column('baby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'diapers', 'babies', ['baby_id'], ['id'])
    op.add_column('feedings', sa.Column('baby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feedings', 'babies', ['baby_id'], ['id'])
    op.add_column('growths', sa.Column('baby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'growths', 'babies', ['baby_id'], ['id'])
    op.add_column('schedules', sa.Column('baby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'schedules', 'babies', ['baby_id'], ['id'])
    op.add_column('sleeps', sa.Column('baby_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sleeps', 'babies', ['baby_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sleeps', type_='foreignkey')
    op.drop_column('sleeps', 'baby_id')
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.drop_column('schedules', 'baby_id')
    op.drop_constraint(None, 'growths', type_='foreignkey')
    op.drop_column('growths', 'baby_id')
    op.drop_constraint(None, 'feedings', type_='foreignkey')
    op.drop_column('feedings', 'baby_id')
    op.drop_constraint(None, 'diapers', type_='foreignkey')
    op.drop_column('diapers', 'baby_id')
    op.drop_constraint(None, 'contractions', type_='foreignkey')
    op.drop_column('contractions', 'baby_id')
    op.drop_table('family_users')
    op.drop_index(op.f('ix_babies_id'), table_name='babies')
    op.drop_table('babies')
    op.drop_index(op.f('ix_families_invite_code'), table_name='families')
    op.drop_index(op.f('ix_families_id'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
