"""add_baby_permissions_table

Revision ID: 162383dfc515
Revises: 7a2488f01c46
Create Date: 2026-02-12 14:08:33.653758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '162383dfc515'
down_revision: Union[str, None] = '7a2488f01c46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baby_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('baby_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['baby_id'], ['babies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('baby_id', 'user_id', 'record_type', name='uix_baby_user_record_type')
    )
    op.create_index(op.f('ix_baby_permissions_id'), 'baby_permissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_baby_permissions_id'), table_name='baby_permissions')
    op.drop_table('baby_permissions')
    # ### end Alembic commands ###
