"""add due_date to babies

Revision ID: 7a2488f01c46
Revises: ca9d8d3bbd31
Create Date: 2026-02-11 14:05:02.848389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a2488f01c46'
down_revision: Union[str, None] = 'ca9d8d3bbd31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('babies', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
